/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.RaidTraditionalKnowledgeLabel;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaidTraditionalKnowledgeLabelRecord extends UpdatableRecordImpl<RaidTraditionalKnowledgeLabelRecord> implements Record2<String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>api_svc.raid_traditional_knowledge_label.raid_name</code>.
     */
    public RaidTraditionalKnowledgeLabelRecord setRaidName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for
     * <code>api_svc.raid_traditional_knowledge_label.raid_name</code>.
     */
    public String getRaidName() {
        return (String) get(0);
    }

    /**
     * Setter for
     * <code>api_svc.raid_traditional_knowledge_label.traditional_knowledge_label_id</code>.
     */
    public RaidTraditionalKnowledgeLabelRecord setTraditionalKnowledgeLabelId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>api_svc.raid_traditional_knowledge_label.traditional_knowledge_label_id</code>.
     */
    public Integer getTraditionalKnowledgeLabelId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return RaidTraditionalKnowledgeLabel.RAID_TRADITIONAL_KNOWLEDGE_LABEL.RAID_NAME;
    }

    @Override
    public Field<Integer> field2() {
        return RaidTraditionalKnowledgeLabel.RAID_TRADITIONAL_KNOWLEDGE_LABEL.TRADITIONAL_KNOWLEDGE_LABEL_ID;
    }

    @Override
    public String component1() {
        return getRaidName();
    }

    @Override
    public Integer component2() {
        return getTraditionalKnowledgeLabelId();
    }

    @Override
    public String value1() {
        return getRaidName();
    }

    @Override
    public Integer value2() {
        return getTraditionalKnowledgeLabelId();
    }

    @Override
    public RaidTraditionalKnowledgeLabelRecord value1(String value) {
        setRaidName(value);
        return this;
    }

    @Override
    public RaidTraditionalKnowledgeLabelRecord value2(Integer value) {
        setTraditionalKnowledgeLabelId(value);
        return this;
    }

    @Override
    public RaidTraditionalKnowledgeLabelRecord values(String value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaidTraditionalKnowledgeLabelRecord
     */
    public RaidTraditionalKnowledgeLabelRecord() {
        super(RaidTraditionalKnowledgeLabel.RAID_TRADITIONAL_KNOWLEDGE_LABEL);
    }

    /**
     * Create a detached, initialised RaidTraditionalKnowledgeLabelRecord
     */
    public RaidTraditionalKnowledgeLabelRecord(String raidName, Integer traditionalKnowledgeLabelId) {
        super(RaidTraditionalKnowledgeLabel.RAID_TRADITIONAL_KNOWLEDGE_LABEL);

        setRaidName(raidName);
        setTraditionalKnowledgeLabelId(traditionalKnowledgeLabelId);
    }
}
