/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.enums.Metaschema;
import au.org.raid.db.jooq.tables.Raid;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaidRecord extends UpdatableRecordImpl<RaidRecord> implements Record11<String, Long, String, Integer, String, Boolean, Metaschema, JSONB, LocalDate, LocalDateTime, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.raid.handle</code>. Holds the handle (i.e. just
     * prefix/suffix) not the URL.  Usually quite  short in production, but the
     * max length is set to accommodate int and load testing.
     */
    public RaidRecord setHandle(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.handle</code>. Holds the handle (i.e. just
     * prefix/suffix) not the URL.  Usually quite  short in production, but the
     * max length is set to accommodate int and load testing.
     */
    public String getHandle() {
        return (String) get(0);
    }

    /**
     * Setter for <code>api_svc.raid.service_point_id</code>.
     */
    public RaidRecord setServicePointId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.service_point_id</code>.
     */
    public Long getServicePointId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>api_svc.raid.url</code>. The value that we set as the
     * `URL` property via ARDC APIDS.
     *   Example: `https://demo.raido-infra.com/raid/123.456/789`. 
     *   The global handle regisrty url (e.g.
     * `https://hdl.handle.net/123.456/789`) 
     *   will redirect to this value.
     */
    public RaidRecord setUrl(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.url</code>. The value that we set as the
     * `URL` property via ARDC APIDS.
     *   Example: `https://demo.raido-infra.com/raid/123.456/789`. 
     *   The global handle regisrty url (e.g.
     * `https://hdl.handle.net/123.456/789`) 
     *   will redirect to this value.
     */
    public String getUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>api_svc.raid.url_index</code>. The `index` of the URL
     * property in APIDS. This can be different if we change
     *   how we mint URL values via APIDS.
     */
    public RaidRecord setUrlIndex(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.url_index</code>. The `index` of the URL
     * property in APIDS. This can be different if we change
     *   how we mint URL values via APIDS.
     */
    public Integer getUrlIndex() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>api_svc.raid.primary_title</code>.
     */
    public RaidRecord setPrimaryTitle(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.primary_title</code>.
     */
    public String getPrimaryTitle() {
        return (String) get(4);
    }

    /**
     * Setter for <code>api_svc.raid.confidential</code>.
     */
    public RaidRecord setConfidential(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.confidential</code>.
     */
    public Boolean getConfidential() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>api_svc.raid.metadata_schema</code>. Identifies the
     * structure of the data in the metadata column
     */
    public RaidRecord setMetadataSchema(Metaschema value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.metadata_schema</code>. Identifies the
     * structure of the data in the metadata column
     */
    public Metaschema getMetadataSchema() {
        return (Metaschema) get(6);
    }

    /**
     * Setter for <code>api_svc.raid.metadata</code>.
     */
    public RaidRecord setMetadata(JSONB value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.metadata</code>.
     */
    public JSONB getMetadata() {
        return (JSONB) get(7);
    }

    /**
     * Setter for <code>api_svc.raid.start_date</code>.
     */
    public RaidRecord setStartDate(LocalDate value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.start_date</code>.
     */
    public LocalDate getStartDate() {
        return (LocalDate) get(8);
    }

    /**
     * Setter for <code>api_svc.raid.date_created</code>.
     */
    public RaidRecord setDateCreated(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.date_created</code>.
     */
    public LocalDateTime getDateCreated() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>api_svc.raid.version</code>.
     */
    public RaidRecord setVersion(Integer value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<String, Long, String, Integer, String, Boolean, Metaschema, JSONB, LocalDate, LocalDateTime, Integer> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<String, Long, String, Integer, String, Boolean, Metaschema, JSONB, LocalDate, LocalDateTime, Integer> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Raid.RAID.HANDLE;
    }

    @Override
    public Field<Long> field2() {
        return Raid.RAID.SERVICE_POINT_ID;
    }

    @Override
    public Field<String> field3() {
        return Raid.RAID.URL;
    }

    @Override
    public Field<Integer> field4() {
        return Raid.RAID.URL_INDEX;
    }

    @Override
    public Field<String> field5() {
        return Raid.RAID.PRIMARY_TITLE;
    }

    @Override
    public Field<Boolean> field6() {
        return Raid.RAID.CONFIDENTIAL;
    }

    @Override
    public Field<Metaschema> field7() {
        return Raid.RAID.METADATA_SCHEMA;
    }

    @Override
    public Field<JSONB> field8() {
        return Raid.RAID.METADATA;
    }

    @Override
    public Field<LocalDate> field9() {
        return Raid.RAID.START_DATE;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return Raid.RAID.DATE_CREATED;
    }

    @Override
    public Field<Integer> field11() {
        return Raid.RAID.VERSION;
    }

    @Override
    public String component1() {
        return getHandle();
    }

    @Override
    public Long component2() {
        return getServicePointId();
    }

    @Override
    public String component3() {
        return getUrl();
    }

    @Override
    public Integer component4() {
        return getUrlIndex();
    }

    @Override
    public String component5() {
        return getPrimaryTitle();
    }

    @Override
    public Boolean component6() {
        return getConfidential();
    }

    @Override
    public Metaschema component7() {
        return getMetadataSchema();
    }

    @Override
    public JSONB component8() {
        return getMetadata();
    }

    @Override
    public LocalDate component9() {
        return getStartDate();
    }

    @Override
    public LocalDateTime component10() {
        return getDateCreated();
    }

    @Override
    public Integer component11() {
        return getVersion();
    }

    @Override
    public String value1() {
        return getHandle();
    }

    @Override
    public Long value2() {
        return getServicePointId();
    }

    @Override
    public String value3() {
        return getUrl();
    }

    @Override
    public Integer value4() {
        return getUrlIndex();
    }

    @Override
    public String value5() {
        return getPrimaryTitle();
    }

    @Override
    public Boolean value6() {
        return getConfidential();
    }

    @Override
    public Metaschema value7() {
        return getMetadataSchema();
    }

    @Override
    public JSONB value8() {
        return getMetadata();
    }

    @Override
    public LocalDate value9() {
        return getStartDate();
    }

    @Override
    public LocalDateTime value10() {
        return getDateCreated();
    }

    @Override
    public Integer value11() {
        return getVersion();
    }

    @Override
    public RaidRecord value1(String value) {
        setHandle(value);
        return this;
    }

    @Override
    public RaidRecord value2(Long value) {
        setServicePointId(value);
        return this;
    }

    @Override
    public RaidRecord value3(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public RaidRecord value4(Integer value) {
        setUrlIndex(value);
        return this;
    }

    @Override
    public RaidRecord value5(String value) {
        setPrimaryTitle(value);
        return this;
    }

    @Override
    public RaidRecord value6(Boolean value) {
        setConfidential(value);
        return this;
    }

    @Override
    public RaidRecord value7(Metaschema value) {
        setMetadataSchema(value);
        return this;
    }

    @Override
    public RaidRecord value8(JSONB value) {
        setMetadata(value);
        return this;
    }

    @Override
    public RaidRecord value9(LocalDate value) {
        setStartDate(value);
        return this;
    }

    @Override
    public RaidRecord value10(LocalDateTime value) {
        setDateCreated(value);
        return this;
    }

    @Override
    public RaidRecord value11(Integer value) {
        setVersion(value);
        return this;
    }

    @Override
    public RaidRecord values(String value1, Long value2, String value3, Integer value4, String value5, Boolean value6, Metaschema value7, JSONB value8, LocalDate value9, LocalDateTime value10, Integer value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaidRecord
     */
    public RaidRecord() {
        super(Raid.RAID);
    }

    /**
     * Create a detached, initialised RaidRecord
     */
    public RaidRecord(String handle, Long servicePointId, String url, Integer urlIndex, String primaryTitle, Boolean confidential, Metaschema metadataSchema, JSONB metadata, LocalDate startDate, LocalDateTime dateCreated, Integer version) {
        super(Raid.RAID);

        setHandle(handle);
        setServicePointId(servicePointId);
        setUrl(url);
        setUrlIndex(urlIndex);
        setPrimaryTitle(primaryTitle);
        setConfidential(confidential);
        setMetadataSchema(metadataSchema);
        setMetadata(metadata);
        setStartDate(startDate);
        setDateCreated(dateCreated);
        setVersion(version);
    }
}
