/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.RaidSubject;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaidSubjectRecord extends UpdatableRecordImpl<RaidSubjectRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.raid_subject.id</code>.
     */
    public RaidSubjectRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_subject.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.raid_subject.raid_name</code>.
     */
    public RaidSubjectRecord setRaidName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_subject.raid_name</code>.
     */
    public String getRaidName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.raid_subject.subject_type_id</code>.
     */
    public RaidSubjectRecord setSubjectTypeId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_subject.subject_type_id</code>.
     */
    public String getSubjectTypeId() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return RaidSubject.RAID_SUBJECT.ID;
    }

    @Override
    public Field<String> field2() {
        return RaidSubject.RAID_SUBJECT.RAID_NAME;
    }

    @Override
    public Field<String> field3() {
        return RaidSubject.RAID_SUBJECT.SUBJECT_TYPE_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getRaidName();
    }

    @Override
    public String component3() {
        return getSubjectTypeId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getRaidName();
    }

    @Override
    public String value3() {
        return getSubjectTypeId();
    }

    @Override
    public RaidSubjectRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public RaidSubjectRecord value2(String value) {
        setRaidName(value);
        return this;
    }

    @Override
    public RaidSubjectRecord value3(String value) {
        setSubjectTypeId(value);
        return this;
    }

    @Override
    public RaidSubjectRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaidSubjectRecord
     */
    public RaidSubjectRecord() {
        super(RaidSubject.RAID_SUBJECT);
    }

    /**
     * Create a detached, initialised RaidSubjectRecord
     */
    public RaidSubjectRecord(Integer id, String raidName, String subjectTypeId) {
        super(RaidSubject.RAID_SUBJECT);

        setId(id);
        setRaidName(raidName);
        setSubjectTypeId(subjectTypeId);
    }
}
