/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.RaidSubject;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaidSubjectRecord extends UpdatableRecordImpl<RaidSubjectRecord> implements Record4<String, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.raid_subject.raid_name</code>.
     */
    public RaidSubjectRecord setRaidName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_subject.raid_name</code>.
     */
    public String getRaidName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>api_svc.raid_subject.subject_type_id</code>.
     */
    public RaidSubjectRecord setSubjectTypeId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_subject.subject_type_id</code>.
     */
    public String getSubjectTypeId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.raid_subject.keyword</code>.
     */
    public RaidSubjectRecord setKeyword(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_subject.keyword</code>.
     */
    public String getKeyword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>api_svc.raid_subject.keyword_language_id</code>.
     */
    public RaidSubjectRecord setKeywordLanguageId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_subject.keyword_language_id</code>.
     */
    public Integer getKeywordLanguageId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return RaidSubject.RAID_SUBJECT.RAID_NAME;
    }

    @Override
    public Field<String> field2() {
        return RaidSubject.RAID_SUBJECT.SUBJECT_TYPE_ID;
    }

    @Override
    public Field<String> field3() {
        return RaidSubject.RAID_SUBJECT.KEYWORD;
    }

    @Override
    public Field<Integer> field4() {
        return RaidSubject.RAID_SUBJECT.KEYWORD_LANGUAGE_ID;
    }

    @Override
    public String component1() {
        return getRaidName();
    }

    @Override
    public String component2() {
        return getSubjectTypeId();
    }

    @Override
    public String component3() {
        return getKeyword();
    }

    @Override
    public Integer component4() {
        return getKeywordLanguageId();
    }

    @Override
    public String value1() {
        return getRaidName();
    }

    @Override
    public String value2() {
        return getSubjectTypeId();
    }

    @Override
    public String value3() {
        return getKeyword();
    }

    @Override
    public Integer value4() {
        return getKeywordLanguageId();
    }

    @Override
    public RaidSubjectRecord value1(String value) {
        setRaidName(value);
        return this;
    }

    @Override
    public RaidSubjectRecord value2(String value) {
        setSubjectTypeId(value);
        return this;
    }

    @Override
    public RaidSubjectRecord value3(String value) {
        setKeyword(value);
        return this;
    }

    @Override
    public RaidSubjectRecord value4(Integer value) {
        setKeywordLanguageId(value);
        return this;
    }

    @Override
    public RaidSubjectRecord values(String value1, String value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaidSubjectRecord
     */
    public RaidSubjectRecord() {
        super(RaidSubject.RAID_SUBJECT);
    }

    /**
     * Create a detached, initialised RaidSubjectRecord
     */
    public RaidSubjectRecord(String raidName, String subjectTypeId, String keyword, Integer keywordLanguageId) {
        super(RaidSubject.RAID_SUBJECT);

        setRaidName(raidName);
        setSubjectTypeId(subjectTypeId);
        setKeyword(keyword);
        setKeywordLanguageId(keywordLanguageId);
    }
}
