/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.RaidOrganisation;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaidOrganisationRecord extends UpdatableRecordImpl<RaidOrganisationRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.raid_organisation.id</code>.
     */
    public RaidOrganisationRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_organisation.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.raid_organisation.handle</code>.
     */
    public RaidOrganisationRecord setHandle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_organisation.handle</code>.
     */
    public String getHandle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.raid_organisation.organisation_id</code>.
     */
    public RaidOrganisationRecord setOrganisationId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_organisation.organisation_id</code>.
     */
    public Integer getOrganisationId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return RaidOrganisation.RAID_ORGANISATION.ID;
    }

    @Override
    public Field<String> field2() {
        return RaidOrganisation.RAID_ORGANISATION.HANDLE;
    }

    @Override
    public Field<Integer> field3() {
        return RaidOrganisation.RAID_ORGANISATION.ORGANISATION_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getHandle();
    }

    @Override
    public Integer component3() {
        return getOrganisationId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getHandle();
    }

    @Override
    public Integer value3() {
        return getOrganisationId();
    }

    @Override
    public RaidOrganisationRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public RaidOrganisationRecord value2(String value) {
        setHandle(value);
        return this;
    }

    @Override
    public RaidOrganisationRecord value3(Integer value) {
        setOrganisationId(value);
        return this;
    }

    @Override
    public RaidOrganisationRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaidOrganisationRecord
     */
    public RaidOrganisationRecord() {
        super(RaidOrganisation.RAID_ORGANISATION);
    }

    /**
     * Create a detached, initialised RaidOrganisationRecord
     */
    public RaidOrganisationRecord(Integer id, String handle, Integer organisationId) {
        super(RaidOrganisation.RAID_ORGANISATION);

        setId(id);
        setHandle(handle);
        setOrganisationId(organisationId);
    }
}
