/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.RaidContributorRole;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaidContributorRoleRecord extends UpdatableRecordImpl<RaidContributorRoleRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.raid_contributor_role.id</code>.
     */
    public RaidContributorRoleRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_contributor_role.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>api_svc.raid_contributor_role.raid_contributor_id</code>.
     */
    public RaidContributorRoleRecord setRaidContributorId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>api_svc.raid_contributor_role.raid_contributor_id</code>.
     */
    public Integer getRaidContributorId() {
        return (Integer) get(1);
    }

    /**
     * Setter for
     * <code>api_svc.raid_contributor_role.contributor_role_id</code>.
     */
    public RaidContributorRoleRecord setContributorRoleId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>api_svc.raid_contributor_role.contributor_role_id</code>.
     */
    public Integer getContributorRoleId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return RaidContributorRole.RAID_CONTRIBUTOR_ROLE.ID;
    }

    @Override
    public Field<Integer> field2() {
        return RaidContributorRole.RAID_CONTRIBUTOR_ROLE.RAID_CONTRIBUTOR_ID;
    }

    @Override
    public Field<Integer> field3() {
        return RaidContributorRole.RAID_CONTRIBUTOR_ROLE.CONTRIBUTOR_ROLE_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getRaidContributorId();
    }

    @Override
    public Integer component3() {
        return getContributorRoleId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getRaidContributorId();
    }

    @Override
    public Integer value3() {
        return getContributorRoleId();
    }

    @Override
    public RaidContributorRoleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public RaidContributorRoleRecord value2(Integer value) {
        setRaidContributorId(value);
        return this;
    }

    @Override
    public RaidContributorRoleRecord value3(Integer value) {
        setContributorRoleId(value);
        return this;
    }

    @Override
    public RaidContributorRoleRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaidContributorRoleRecord
     */
    public RaidContributorRoleRecord() {
        super(RaidContributorRole.RAID_CONTRIBUTOR_ROLE);
    }

    /**
     * Create a detached, initialised RaidContributorRoleRecord
     */
    public RaidContributorRoleRecord(Integer id, Integer raidContributorId, Integer contributorRoleId) {
        super(RaidContributorRole.RAID_CONTRIBUTOR_ROLE);

        setId(id);
        setRaidContributorId(raidContributorId);
        setContributorRoleId(contributorRoleId);
    }
}
