/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.ServicePoint;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServicePointRecord extends UpdatableRecordImpl<ServicePointRecord> implements Record9<Long, String, String, String, String, Boolean, String, String, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.service_point.id</code>.
     */
    public ServicePointRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.service_point.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>api_svc.service_point.name</code>.
     */
    public ServicePointRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.service_point.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.service_point.search_content</code>. Trimmed
     * lowercase only
     */
    public ServicePointRecord setSearchContent(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.service_point.search_content</code>. Trimmed
     * lowercase only
     */
    public String getSearchContent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>api_svc.service_point.admin_email</code>.
     */
    public ServicePointRecord setAdminEmail(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.service_point.admin_email</code>.
     */
    public String getAdminEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>api_svc.service_point.tech_email</code>.
     */
    public ServicePointRecord setTechEmail(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.service_point.tech_email</code>.
     */
    public String getTechEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>api_svc.service_point.enabled</code>.
     */
    public ServicePointRecord setEnabled(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.service_point.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>api_svc.service_point.lower_name</code>.
     */
    public ServicePointRecord setLowerName(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.service_point.lower_name</code>.
     */
    public String getLowerName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>api_svc.service_point.identifier_owner</code>.
     */
    public ServicePointRecord setIdentifierOwner(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.service_point.identifier_owner</code>.
     */
    public String getIdentifierOwner() {
        return (String) get(7);
    }

    /**
     * Setter for <code>api_svc.service_point.app_writes_enabled</code>.
     */
    public ServicePointRecord setAppWritesEnabled(Boolean value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.service_point.app_writes_enabled</code>.
     */
    public Boolean getAppWritesEnabled() {
        return (Boolean) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, String, String, Boolean, String, String, Boolean> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, String, String, String, String, Boolean, String, String, Boolean> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ServicePoint.SERVICE_POINT.ID;
    }

    @Override
    public Field<String> field2() {
        return ServicePoint.SERVICE_POINT.NAME;
    }

    @Override
    public Field<String> field3() {
        return ServicePoint.SERVICE_POINT.SEARCH_CONTENT;
    }

    @Override
    public Field<String> field4() {
        return ServicePoint.SERVICE_POINT.ADMIN_EMAIL;
    }

    @Override
    public Field<String> field5() {
        return ServicePoint.SERVICE_POINT.TECH_EMAIL;
    }

    @Override
    public Field<Boolean> field6() {
        return ServicePoint.SERVICE_POINT.ENABLED;
    }

    @Override
    public Field<String> field7() {
        return ServicePoint.SERVICE_POINT.LOWER_NAME;
    }

    @Override
    public Field<String> field8() {
        return ServicePoint.SERVICE_POINT.IDENTIFIER_OWNER;
    }

    @Override
    public Field<Boolean> field9() {
        return ServicePoint.SERVICE_POINT.APP_WRITES_ENABLED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getSearchContent();
    }

    @Override
    public String component4() {
        return getAdminEmail();
    }

    @Override
    public String component5() {
        return getTechEmail();
    }

    @Override
    public Boolean component6() {
        return getEnabled();
    }

    @Override
    public String component7() {
        return getLowerName();
    }

    @Override
    public String component8() {
        return getIdentifierOwner();
    }

    @Override
    public Boolean component9() {
        return getAppWritesEnabled();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getSearchContent();
    }

    @Override
    public String value4() {
        return getAdminEmail();
    }

    @Override
    public String value5() {
        return getTechEmail();
    }

    @Override
    public Boolean value6() {
        return getEnabled();
    }

    @Override
    public String value7() {
        return getLowerName();
    }

    @Override
    public String value8() {
        return getIdentifierOwner();
    }

    @Override
    public Boolean value9() {
        return getAppWritesEnabled();
    }

    @Override
    public ServicePointRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ServicePointRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ServicePointRecord value3(String value) {
        setSearchContent(value);
        return this;
    }

    @Override
    public ServicePointRecord value4(String value) {
        setAdminEmail(value);
        return this;
    }

    @Override
    public ServicePointRecord value5(String value) {
        setTechEmail(value);
        return this;
    }

    @Override
    public ServicePointRecord value6(Boolean value) {
        setEnabled(value);
        return this;
    }

    @Override
    public ServicePointRecord value7(String value) {
        setLowerName(value);
        return this;
    }

    @Override
    public ServicePointRecord value8(String value) {
        setIdentifierOwner(value);
        return this;
    }

    @Override
    public ServicePointRecord value9(Boolean value) {
        setAppWritesEnabled(value);
        return this;
    }

    @Override
    public ServicePointRecord values(Long value1, String value2, String value3, String value4, String value5, Boolean value6, String value7, String value8, Boolean value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServicePointRecord
     */
    public ServicePointRecord() {
        super(ServicePoint.SERVICE_POINT);
    }

    /**
     * Create a detached, initialised ServicePointRecord
     */
    public ServicePointRecord(Long id, String name, String searchContent, String adminEmail, String techEmail, Boolean enabled, String lowerName, String identifierOwner, Boolean appWritesEnabled) {
        super(ServicePoint.SERVICE_POINT);

        setId(id);
        setName(name);
        setSearchContent(searchContent);
        setAdminEmail(adminEmail);
        setTechEmail(techEmail);
        setEnabled(enabled);
        setLowerName(lowerName);
        setIdentifierOwner(identifierOwner);
        setAppWritesEnabled(appWritesEnabled);
    }
}
