/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.SpatialCoverageSchema;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpatialCoverageSchemaRecord extends UpdatableRecordImpl<SpatialCoverageSchemaRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.spatial_coverage_schema.id</code>.
     */
    public SpatialCoverageSchemaRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.spatial_coverage_schema.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.spatial_coverage_schema.schema_uri</code>.
     */
    public SpatialCoverageSchemaRecord setSchemaUri(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.spatial_coverage_schema.schema_uri</code>.
     */
    public String getSchemaUri() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return SpatialCoverageSchema.SPATIAL_COVERAGE_SCHEMA.ID;
    }

    @Override
    public Field<String> field2() {
        return SpatialCoverageSchema.SPATIAL_COVERAGE_SCHEMA.SCHEMA_URI;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getSchemaUri();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getSchemaUri();
    }

    @Override
    public SpatialCoverageSchemaRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SpatialCoverageSchemaRecord value2(String value) {
        setSchemaUri(value);
        return this;
    }

    @Override
    public SpatialCoverageSchemaRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpatialCoverageSchemaRecord
     */
    public SpatialCoverageSchemaRecord() {
        super(SpatialCoverageSchema.SPATIAL_COVERAGE_SCHEMA);
    }

    /**
     * Create a detached, initialised SpatialCoverageSchemaRecord
     */
    public SpatialCoverageSchemaRecord(Integer id, String schemaUri) {
        super(SpatialCoverageSchema.SPATIAL_COVERAGE_SCHEMA);

        setId(id);
        setSchemaUri(schemaUri);
    }
}
