/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.TraditionalKnowledgeNotice;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TraditionalKnowledgeNoticeRecord extends UpdatableRecordImpl<TraditionalKnowledgeNoticeRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.traditional_knowledge_notice.id</code>.
     */
    public TraditionalKnowledgeNoticeRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.traditional_knowledge_notice.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.traditional_knowledge_notice.uri</code>.
     */
    public TraditionalKnowledgeNoticeRecord setUri(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.traditional_knowledge_notice.uri</code>.
     */
    public String getUri() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.traditional_knowledge_notice.schema_id</code>.
     */
    public TraditionalKnowledgeNoticeRecord setSchemaId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.traditional_knowledge_notice.schema_id</code>.
     */
    public Integer getSchemaId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TraditionalKnowledgeNotice.TRADITIONAL_KNOWLEDGE_NOTICE.ID;
    }

    @Override
    public Field<String> field2() {
        return TraditionalKnowledgeNotice.TRADITIONAL_KNOWLEDGE_NOTICE.URI;
    }

    @Override
    public Field<Integer> field3() {
        return TraditionalKnowledgeNotice.TRADITIONAL_KNOWLEDGE_NOTICE.SCHEMA_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUri();
    }

    @Override
    public Integer component3() {
        return getSchemaId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUri();
    }

    @Override
    public Integer value3() {
        return getSchemaId();
    }

    @Override
    public TraditionalKnowledgeNoticeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TraditionalKnowledgeNoticeRecord value2(String value) {
        setUri(value);
        return this;
    }

    @Override
    public TraditionalKnowledgeNoticeRecord value3(Integer value) {
        setSchemaId(value);
        return this;
    }

    @Override
    public TraditionalKnowledgeNoticeRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TraditionalKnowledgeNoticeRecord
     */
    public TraditionalKnowledgeNoticeRecord() {
        super(TraditionalKnowledgeNotice.TRADITIONAL_KNOWLEDGE_NOTICE);
    }

    /**
     * Create a detached, initialised TraditionalKnowledgeNoticeRecord
     */
    public TraditionalKnowledgeNoticeRecord(Integer id, String uri, Integer schemaId) {
        super(TraditionalKnowledgeNotice.TRADITIONAL_KNOWLEDGE_NOTICE);

        setId(id);
        setUri(uri);
        setSchemaId(schemaId);
    }
}
