/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.api_svc.tables.records;


import au.org.raid.db.jooq.api_svc.tables.Language;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LanguageRecord extends TableRecordImpl<LanguageRecord> implements Record3<String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.language.id</code>.
     */
    public LanguageRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.language.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>api_svc.language.name</code>.
     */
    public LanguageRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.language.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.language.schema_id</code>.
     */
    public LanguageRecord setSchemaId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.language.schema_id</code>.
     */
    public Integer getSchemaId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Language.LANGUAGE.ID;
    }

    @Override
    public Field<String> field2() {
        return Language.LANGUAGE.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return Language.LANGUAGE.SCHEMA_ID;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getSchemaId();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getSchemaId();
    }

    @Override
    public LanguageRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public LanguageRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public LanguageRecord value3(Integer value) {
        setSchemaId(value);
        return this;
    }

    @Override
    public LanguageRecord values(String value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LanguageRecord
     */
    public LanguageRecord() {
        super(Language.LANGUAGE);
    }

    /**
     * Create a detached, initialised LanguageRecord
     */
    public LanguageRecord(String id, String name, Integer schemaId) {
        super(Language.LANGUAGE);

        setId(id);
        setName(name);
        setSchemaId(schemaId);
    }
}
