/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.api_svc.tables.records;


import au.org.raid.db.jooq.api_svc.tables.RelatedObjectCategory;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RelatedObjectCategoryRecord extends UpdatableRecordImpl<RelatedObjectCategoryRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.related_object_category.scheme_id</code>.
     */
    public RelatedObjectCategoryRecord setSchemeId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.related_object_category.scheme_id</code>.
     */
    public Integer getSchemeId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.related_object_category.uri</code>.
     */
    public RelatedObjectCategoryRecord setUri(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.related_object_category.uri</code>.
     */
    public String getUri() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return RelatedObjectCategory.RELATED_OBJECT_CATEGORY.SCHEME_ID;
    }

    @Override
    public Field<String> field2() {
        return RelatedObjectCategory.RELATED_OBJECT_CATEGORY.URI;
    }

    @Override
    public Integer component1() {
        return getSchemeId();
    }

    @Override
    public String component2() {
        return getUri();
    }

    @Override
    public Integer value1() {
        return getSchemeId();
    }

    @Override
    public String value2() {
        return getUri();
    }

    @Override
    public RelatedObjectCategoryRecord value1(Integer value) {
        setSchemeId(value);
        return this;
    }

    @Override
    public RelatedObjectCategoryRecord value2(String value) {
        setUri(value);
        return this;
    }

    @Override
    public RelatedObjectCategoryRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RelatedObjectCategoryRecord
     */
    public RelatedObjectCategoryRecord() {
        super(RelatedObjectCategory.RELATED_OBJECT_CATEGORY);
    }

    /**
     * Create a detached, initialised RelatedObjectCategoryRecord
     */
    public RelatedObjectCategoryRecord(Integer schemeId, String uri) {
        super(RelatedObjectCategory.RELATED_OBJECT_CATEGORY);

        setSchemeId(schemeId);
        setUri(uri);
    }
}
