/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables;


import au.org.raid.db.jooq.ApiSvc;
import au.org.raid.db.jooq.Keys;
import au.org.raid.db.jooq.tables.records.ContributorRoleRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContributorRole extends TableImpl<ContributorRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>api_svc.contributor_role</code>
     */
    public static final ContributorRole CONTRIBUTOR_ROLE = new ContributorRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContributorRoleRecord> getRecordType() {
        return ContributorRoleRecord.class;
    }

    /**
     * The column <code>api_svc.contributor_role.id</code>.
     */
    public final TableField<ContributorRoleRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>api_svc.contributor_role.uri</code>.
     */
    public final TableField<ContributorRoleRecord, String> URI = createField(DSL.name("uri"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>api_svc.contributor_role.schema_id</code>.
     */
    public final TableField<ContributorRoleRecord, Integer> SCHEMA_ID = createField(DSL.name("schema_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private ContributorRole(Name alias, Table<ContributorRoleRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContributorRole(Name alias, Table<ContributorRoleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>api_svc.contributor_role</code> table reference
     */
    public ContributorRole(String alias) {
        this(DSL.name(alias), CONTRIBUTOR_ROLE);
    }

    /**
     * Create an aliased <code>api_svc.contributor_role</code> table reference
     */
    public ContributorRole(Name alias) {
        this(alias, CONTRIBUTOR_ROLE);
    }

    /**
     * Create a <code>api_svc.contributor_role</code> table reference
     */
    public ContributorRole() {
        this(DSL.name("contributor_role"), null);
    }

    public <O extends Record> ContributorRole(Table<O> child, ForeignKey<O, ContributorRoleRecord> key) {
        super(child, key, CONTRIBUTOR_ROLE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ApiSvc.API_SVC;
    }

    @Override
    public Identity<ContributorRoleRecord, Integer> getIdentity() {
        return (Identity<ContributorRoleRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ContributorRoleRecord> getPrimaryKey() {
        return Keys.CONTRIBUTOR_ROLE_NEW_PKEY;
    }

    @Override
    public ContributorRole as(String alias) {
        return new ContributorRole(DSL.name(alias), this);
    }

    @Override
    public ContributorRole as(Name alias) {
        return new ContributorRole(alias, this);
    }

    @Override
    public ContributorRole as(Table<?> alias) {
        return new ContributorRole(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContributorRole rename(String name) {
        return new ContributorRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ContributorRole rename(Name name) {
        return new ContributorRole(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ContributorRole rename(Table<?> name) {
        return new ContributorRole(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Integer, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Integer, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
