/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables;


import au.org.raid.db.jooq.ApiSvc;
import au.org.raid.db.jooq.Keys;
import au.org.raid.db.jooq.tables.records.OrganisationRoleSchemaRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrganisationRoleSchema extends TableImpl<OrganisationRoleSchemaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>api_svc.organisation_role_schema</code>
     */
    public static final OrganisationRoleSchema ORGANISATION_ROLE_SCHEMA = new OrganisationRoleSchema();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrganisationRoleSchemaRecord> getRecordType() {
        return OrganisationRoleSchemaRecord.class;
    }

    /**
     * The column <code>api_svc.organisation_role_schema.id</code>.
     */
    public final TableField<OrganisationRoleSchemaRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>api_svc.organisation_role_schema.uri</code>.
     */
    public final TableField<OrganisationRoleSchemaRecord, String> URI = createField(DSL.name("uri"), SQLDataType.VARCHAR.nullable(false), this, "");

    private OrganisationRoleSchema(Name alias, Table<OrganisationRoleSchemaRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrganisationRoleSchema(Name alias, Table<OrganisationRoleSchemaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>api_svc.organisation_role_schema</code> table
     * reference
     */
    public OrganisationRoleSchema(String alias) {
        this(DSL.name(alias), ORGANISATION_ROLE_SCHEMA);
    }

    /**
     * Create an aliased <code>api_svc.organisation_role_schema</code> table
     * reference
     */
    public OrganisationRoleSchema(Name alias) {
        this(alias, ORGANISATION_ROLE_SCHEMA);
    }

    /**
     * Create a <code>api_svc.organisation_role_schema</code> table reference
     */
    public OrganisationRoleSchema() {
        this(DSL.name("organisation_role_schema"), null);
    }

    public <O extends Record> OrganisationRoleSchema(Table<O> child, ForeignKey<O, OrganisationRoleSchemaRecord> key) {
        super(child, key, ORGANISATION_ROLE_SCHEMA);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ApiSvc.API_SVC;
    }

    @Override
    public Identity<OrganisationRoleSchemaRecord, Integer> getIdentity() {
        return (Identity<OrganisationRoleSchemaRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<OrganisationRoleSchemaRecord> getPrimaryKey() {
        return Keys.ORGANISATION_ROLE_SCHEMA_PKEY;
    }

    @Override
    public OrganisationRoleSchema as(String alias) {
        return new OrganisationRoleSchema(DSL.name(alias), this);
    }

    @Override
    public OrganisationRoleSchema as(Name alias) {
        return new OrganisationRoleSchema(alias, this);
    }

    @Override
    public OrganisationRoleSchema as(Table<?> alias) {
        return new OrganisationRoleSchema(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrganisationRoleSchema rename(String name) {
        return new OrganisationRoleSchema(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrganisationRoleSchema rename(Name name) {
        return new OrganisationRoleSchema(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrganisationRoleSchema rename(Table<?> name) {
        return new OrganisationRoleSchema(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
