/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables;


import au.org.raid.db.jooq.ApiSvc;
import au.org.raid.db.jooq.Keys;
import au.org.raid.db.jooq.tables.records.OrganisationRoleRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrganisationRole extends TableImpl<OrganisationRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>api_svc.organisation_role</code>
     */
    public static final OrganisationRole ORGANISATION_ROLE = new OrganisationRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrganisationRoleRecord> getRecordType() {
        return OrganisationRoleRecord.class;
    }

    /**
     * The column <code>api_svc.organisation_role.id</code>.
     */
    public final TableField<OrganisationRoleRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>api_svc.organisation_role.uri</code>.
     */
    public final TableField<OrganisationRoleRecord, String> URI = createField(DSL.name("uri"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>api_svc.organisation_role.schema_id</code>.
     */
    public final TableField<OrganisationRoleRecord, Integer> SCHEMA_ID = createField(DSL.name("schema_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private OrganisationRole(Name alias, Table<OrganisationRoleRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrganisationRole(Name alias, Table<OrganisationRoleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>api_svc.organisation_role</code> table reference
     */
    public OrganisationRole(String alias) {
        this(DSL.name(alias), ORGANISATION_ROLE);
    }

    /**
     * Create an aliased <code>api_svc.organisation_role</code> table reference
     */
    public OrganisationRole(Name alias) {
        this(alias, ORGANISATION_ROLE);
    }

    /**
     * Create a <code>api_svc.organisation_role</code> table reference
     */
    public OrganisationRole() {
        this(DSL.name("organisation_role"), null);
    }

    public <O extends Record> OrganisationRole(Table<O> child, ForeignKey<O, OrganisationRoleRecord> key) {
        super(child, key, ORGANISATION_ROLE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ApiSvc.API_SVC;
    }

    @Override
    public Identity<OrganisationRoleRecord, Integer> getIdentity() {
        return (Identity<OrganisationRoleRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<OrganisationRoleRecord> getPrimaryKey() {
        return Keys.ORGANISATION_ROLE_NEW_PKEY;
    }

    @Override
    public OrganisationRole as(String alias) {
        return new OrganisationRole(DSL.name(alias), this);
    }

    @Override
    public OrganisationRole as(Name alias) {
        return new OrganisationRole(alias, this);
    }

    @Override
    public OrganisationRole as(Table<?> alias) {
        return new OrganisationRole(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrganisationRole rename(String name) {
        return new OrganisationRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrganisationRole rename(Name name) {
        return new OrganisationRole(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrganisationRole rename(Table<?> name) {
        return new OrganisationRole(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Integer, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Integer, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
