/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables;


import au.org.raid.db.jooq.ApiSvc;
import au.org.raid.db.jooq.Keys;
import au.org.raid.db.jooq.tables.records.RaidSubjectTypeRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaidSubjectType extends TableImpl<RaidSubjectTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>api_svc.raid_subject_type</code>
     */
    public static final RaidSubjectType RAID_SUBJECT_TYPE = new RaidSubjectType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RaidSubjectTypeRecord> getRecordType() {
        return RaidSubjectTypeRecord.class;
    }

    /**
     * The column <code>api_svc.raid_subject_type.raid_name</code>.
     */
    public final TableField<RaidSubjectTypeRecord, String> RAID_NAME = createField(DSL.name("raid_name"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>api_svc.raid_subject_type.subject_type_id</code>.
     */
    public final TableField<RaidSubjectTypeRecord, String> SUBJECT_TYPE_ID = createField(DSL.name("subject_type_id"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>api_svc.raid_subject_type.keyword</code>.
     */
    public final TableField<RaidSubjectTypeRecord, String> KEYWORD = createField(DSL.name("keyword"), SQLDataType.VARCHAR, this, "");

    private RaidSubjectType(Name alias, Table<RaidSubjectTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private RaidSubjectType(Name alias, Table<RaidSubjectTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>api_svc.raid_subject_type</code> table reference
     */
    public RaidSubjectType(String alias) {
        this(DSL.name(alias), RAID_SUBJECT_TYPE);
    }

    /**
     * Create an aliased <code>api_svc.raid_subject_type</code> table reference
     */
    public RaidSubjectType(Name alias) {
        this(alias, RAID_SUBJECT_TYPE);
    }

    /**
     * Create a <code>api_svc.raid_subject_type</code> table reference
     */
    public RaidSubjectType() {
        this(DSL.name("raid_subject_type"), null);
    }

    public <O extends Record> RaidSubjectType(Table<O> child, ForeignKey<O, RaidSubjectTypeRecord> key) {
        super(child, key, RAID_SUBJECT_TYPE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ApiSvc.API_SVC;
    }

    @Override
    public UniqueKey<RaidSubjectTypeRecord> getPrimaryKey() {
        return Keys.RAID_SUBJECT_TYPE_PKEY;
    }

    @Override
    public List<ForeignKey<RaidSubjectTypeRecord, ?>> getReferences() {
        return Arrays.asList(Keys.RAID_SUBJECT_TYPE__FK_RAID_SUBJECT_TYPE_RAID_NAME, Keys.RAID_SUBJECT_TYPE__FK_RAID_SUBJECT_TYPE_SUBJECT_ID);
    }

    private transient Raid _raid;
    private transient SubjectType _subjectType;

    /**
     * Get the implicit join path to the <code>api_svc.raid</code> table.
     */
    public Raid raid() {
        if (_raid == null)
            _raid = new Raid(this, Keys.RAID_SUBJECT_TYPE__FK_RAID_SUBJECT_TYPE_RAID_NAME);

        return _raid;
    }

    /**
     * Get the implicit join path to the <code>api_svc.subject_type</code>
     * table.
     */
    public SubjectType subjectType() {
        if (_subjectType == null)
            _subjectType = new SubjectType(this, Keys.RAID_SUBJECT_TYPE__FK_RAID_SUBJECT_TYPE_SUBJECT_ID);

        return _subjectType;
    }

    @Override
    public RaidSubjectType as(String alias) {
        return new RaidSubjectType(DSL.name(alias), this);
    }

    @Override
    public RaidSubjectType as(Name alias) {
        return new RaidSubjectType(alias, this);
    }

    @Override
    public RaidSubjectType as(Table<?> alias) {
        return new RaidSubjectType(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RaidSubjectType rename(String name) {
        return new RaidSubjectType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RaidSubjectType rename(Name name) {
        return new RaidSubjectType(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RaidSubjectType rename(Table<?> name) {
        return new RaidSubjectType(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
