/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables;


import au.org.raid.db.jooq.ApiSvc;
import au.org.raid.db.jooq.Keys;
import au.org.raid.db.jooq.tables.records.RelatedRaidRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RelatedRaid extends TableImpl<RelatedRaidRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>api_svc.related_raid</code>
     */
    public static final RelatedRaid RELATED_RAID = new RelatedRaid();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RelatedRaidRecord> getRecordType() {
        return RelatedRaidRecord.class;
    }

    /**
     * The column <code>api_svc.related_raid.handle</code>.
     */
    public final TableField<RelatedRaidRecord, String> HANDLE = createField(DSL.name("handle"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>api_svc.related_raid.related_raid_handle</code>.
     */
    public final TableField<RelatedRaidRecord, String> RELATED_RAID_HANDLE = createField(DSL.name("related_raid_handle"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>api_svc.related_raid.related_raid_type_id</code>.
     */
    public final TableField<RelatedRaidRecord, Integer> RELATED_RAID_TYPE_ID = createField(DSL.name("related_raid_type_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private RelatedRaid(Name alias, Table<RelatedRaidRecord> aliased) {
        this(alias, aliased, null);
    }

    private RelatedRaid(Name alias, Table<RelatedRaidRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>api_svc.related_raid</code> table reference
     */
    public RelatedRaid(String alias) {
        this(DSL.name(alias), RELATED_RAID);
    }

    /**
     * Create an aliased <code>api_svc.related_raid</code> table reference
     */
    public RelatedRaid(Name alias) {
        this(alias, RELATED_RAID);
    }

    /**
     * Create a <code>api_svc.related_raid</code> table reference
     */
    public RelatedRaid() {
        this(DSL.name("related_raid"), null);
    }

    public <O extends Record> RelatedRaid(Table<O> child, ForeignKey<O, RelatedRaidRecord> key) {
        super(child, key, RELATED_RAID);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ApiSvc.API_SVC;
    }

    @Override
    public UniqueKey<RelatedRaidRecord> getPrimaryKey() {
        return Keys.RELATED_RAID_PKEY;
    }

    @Override
    public List<ForeignKey<RelatedRaidRecord, ?>> getReferences() {
        return Arrays.asList(Keys.RELATED_RAID__FK_RELATED_RAID_HANDLE);
    }

    private transient Raid _raid;

    /**
     * Get the implicit join path to the <code>api_svc.raid</code> table.
     */
    public Raid raid() {
        if (_raid == null)
            _raid = new Raid(this, Keys.RELATED_RAID__FK_RELATED_RAID_HANDLE);

        return _raid;
    }

    @Override
    public RelatedRaid as(String alias) {
        return new RelatedRaid(DSL.name(alias), this);
    }

    @Override
    public RelatedRaid as(Name alias) {
        return new RelatedRaid(alias, this);
    }

    @Override
    public RelatedRaid as(Table<?> alias) {
        return new RelatedRaid(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RelatedRaid rename(String name) {
        return new RelatedRaid(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RelatedRaid rename(Name name) {
        return new RelatedRaid(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RelatedRaid rename(Table<?> name) {
        return new RelatedRaid(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
