/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables;


import au.org.raid.db.jooq.ApiSvc;
import au.org.raid.db.jooq.Keys;
import au.org.raid.db.jooq.enums.SchemaStatus;
import au.org.raid.db.jooq.tables.records.SpatialCoverageSchemaRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpatialCoverageSchema extends TableImpl<SpatialCoverageSchemaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>api_svc.spatial_coverage_schema</code>
     */
    public static final SpatialCoverageSchema SPATIAL_COVERAGE_SCHEMA = new SpatialCoverageSchema();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SpatialCoverageSchemaRecord> getRecordType() {
        return SpatialCoverageSchemaRecord.class;
    }

    /**
     * The column <code>api_svc.spatial_coverage_schema.id</code>.
     */
    public final TableField<SpatialCoverageSchemaRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>api_svc.spatial_coverage_schema.uri</code>.
     */
    public final TableField<SpatialCoverageSchemaRecord, String> URI = createField(DSL.name("uri"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>api_svc.spatial_coverage_schema.status</code>.
     */
    public final TableField<SpatialCoverageSchemaRecord, SchemaStatus> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR.asEnumDataType(au.org.raid.db.jooq.enums.SchemaStatus.class), this, "");

    private SpatialCoverageSchema(Name alias, Table<SpatialCoverageSchemaRecord> aliased) {
        this(alias, aliased, null);
    }

    private SpatialCoverageSchema(Name alias, Table<SpatialCoverageSchemaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>api_svc.spatial_coverage_schema</code> table
     * reference
     */
    public SpatialCoverageSchema(String alias) {
        this(DSL.name(alias), SPATIAL_COVERAGE_SCHEMA);
    }

    /**
     * Create an aliased <code>api_svc.spatial_coverage_schema</code> table
     * reference
     */
    public SpatialCoverageSchema(Name alias) {
        this(alias, SPATIAL_COVERAGE_SCHEMA);
    }

    /**
     * Create a <code>api_svc.spatial_coverage_schema</code> table reference
     */
    public SpatialCoverageSchema() {
        this(DSL.name("spatial_coverage_schema"), null);
    }

    public <O extends Record> SpatialCoverageSchema(Table<O> child, ForeignKey<O, SpatialCoverageSchemaRecord> key) {
        super(child, key, SPATIAL_COVERAGE_SCHEMA);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ApiSvc.API_SVC;
    }

    @Override
    public Identity<SpatialCoverageSchemaRecord, Integer> getIdentity() {
        return (Identity<SpatialCoverageSchemaRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<SpatialCoverageSchemaRecord> getPrimaryKey() {
        return Keys.SPATIAL_COVERAGE_SCHEMA_PKEY;
    }

    @Override
    public List<UniqueKey<SpatialCoverageSchemaRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.SPATIAL_COVERAGE_SCHEMA_URI_KEY);
    }

    @Override
    public SpatialCoverageSchema as(String alias) {
        return new SpatialCoverageSchema(DSL.name(alias), this);
    }

    @Override
    public SpatialCoverageSchema as(Name alias) {
        return new SpatialCoverageSchema(alias, this);
    }

    @Override
    public SpatialCoverageSchema as(Table<?> alias) {
        return new SpatialCoverageSchema(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SpatialCoverageSchema rename(String name) {
        return new SpatialCoverageSchema(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SpatialCoverageSchema rename(Name name) {
        return new SpatialCoverageSchema(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SpatialCoverageSchema rename(Table<?> name) {
        return new SpatialCoverageSchema(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, SchemaStatus> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Integer, ? super String, ? super SchemaStatus, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Integer, ? super String, ? super SchemaStatus, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
