/*
 * This file is generated by jOOQ.
 */
package raido.db.jooq.api_svc.tables;


import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import raido.db.jooq.api_svc.ApiSvc;
import raido.db.jooq.api_svc.Keys;
import raido.db.jooq.api_svc.tables.records.OrganisationRoleRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrganisationRole extends TableImpl<OrganisationRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>api_svc.organisation_role</code>
     */
    public static final OrganisationRole ORGANISATION_ROLE = new OrganisationRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrganisationRoleRecord> getRecordType() {
        return OrganisationRoleRecord.class;
    }

    /**
     * The column <code>api_svc.organisation_role.scheme_id</code>.
     */
    public final TableField<OrganisationRoleRecord, Integer> SCHEME_ID = createField(DSL.name("scheme_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>api_svc.organisation_role.uri</code>.
     */
    public final TableField<OrganisationRoleRecord, String> URI = createField(DSL.name("uri"), SQLDataType.VARCHAR.nullable(false), this, "");

    private OrganisationRole(Name alias, Table<OrganisationRoleRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrganisationRole(Name alias, Table<OrganisationRoleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>api_svc.organisation_role</code> table reference
     */
    public OrganisationRole(String alias) {
        this(DSL.name(alias), ORGANISATION_ROLE);
    }

    /**
     * Create an aliased <code>api_svc.organisation_role</code> table reference
     */
    public OrganisationRole(Name alias) {
        this(alias, ORGANISATION_ROLE);
    }

    /**
     * Create a <code>api_svc.organisation_role</code> table reference
     */
    public OrganisationRole() {
        this(DSL.name("organisation_role"), null);
    }

    public <O extends Record> OrganisationRole(Table<O> child, ForeignKey<O, OrganisationRoleRecord> key) {
        super(child, key, ORGANISATION_ROLE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ApiSvc.API_SVC;
    }

    @Override
    public UniqueKey<OrganisationRoleRecord> getPrimaryKey() {
        return Keys.ORGANISATION_ROLE_PKEY;
    }

    @Override
    public List<ForeignKey<OrganisationRoleRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ORGANISATION_ROLE__FK_ORGANISATION_ROLE_TYPE_SCHEME_ID);
    }

    private transient OrganisationRoleScheme _organisationRoleScheme;

    /**
     * Get the implicit join path to the
     * <code>api_svc.organisation_role_scheme</code> table.
     */
    public OrganisationRoleScheme organisationRoleScheme() {
        if (_organisationRoleScheme == null)
            _organisationRoleScheme = new OrganisationRoleScheme(this, Keys.ORGANISATION_ROLE__FK_ORGANISATION_ROLE_TYPE_SCHEME_ID);

        return _organisationRoleScheme;
    }

    @Override
    public OrganisationRole as(String alias) {
        return new OrganisationRole(DSL.name(alias), this);
    }

    @Override
    public OrganisationRole as(Name alias) {
        return new OrganisationRole(alias, this);
    }

    @Override
    public OrganisationRole as(Table<?> alias) {
        return new OrganisationRole(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrganisationRole rename(String name) {
        return new OrganisationRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrganisationRole rename(Name name) {
        return new OrganisationRole(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrganisationRole rename(Table<?> name) {
        return new OrganisationRole(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}