/*
 * This file is generated by jOOQ.
 */
package raido.db.jooq.api_svc.tables;


import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import raido.db.jooq.api_svc.ApiSvc;
import raido.db.jooq.api_svc.Keys;
import raido.db.jooq.api_svc.tables.records.RelatedObjectCategorySchemeRecord;

import java.util.function.Function;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RelatedObjectCategoryScheme extends TableImpl<RelatedObjectCategorySchemeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>api_svc.related_object_category_scheme</code>
     */
    public static final RelatedObjectCategoryScheme RELATED_OBJECT_CATEGORY_SCHEME = new RelatedObjectCategoryScheme();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RelatedObjectCategorySchemeRecord> getRecordType() {
        return RelatedObjectCategorySchemeRecord.class;
    }

    /**
     * The column <code>api_svc.related_object_category_scheme.id</code>.
     */
    public final TableField<RelatedObjectCategorySchemeRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>api_svc.related_object_category_scheme.uri</code>.
     */
    public final TableField<RelatedObjectCategorySchemeRecord, String> URI = createField(DSL.name("uri"), SQLDataType.VARCHAR.nullable(false), this, "");

    private RelatedObjectCategoryScheme(Name alias, Table<RelatedObjectCategorySchemeRecord> aliased) {
        this(alias, aliased, null);
    }

    private RelatedObjectCategoryScheme(Name alias, Table<RelatedObjectCategorySchemeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>api_svc.related_object_category_scheme</code>
     * table reference
     */
    public RelatedObjectCategoryScheme(String alias) {
        this(DSL.name(alias), RELATED_OBJECT_CATEGORY_SCHEME);
    }

    /**
     * Create an aliased <code>api_svc.related_object_category_scheme</code>
     * table reference
     */
    public RelatedObjectCategoryScheme(Name alias) {
        this(alias, RELATED_OBJECT_CATEGORY_SCHEME);
    }

    /**
     * Create a <code>api_svc.related_object_category_scheme</code> table
     * reference
     */
    public RelatedObjectCategoryScheme() {
        this(DSL.name("related_object_category_scheme"), null);
    }

    public <O extends Record> RelatedObjectCategoryScheme(Table<O> child, ForeignKey<O, RelatedObjectCategorySchemeRecord> key) {
        super(child, key, RELATED_OBJECT_CATEGORY_SCHEME);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ApiSvc.API_SVC;
    }

    @Override
    public Identity<RelatedObjectCategorySchemeRecord, Integer> getIdentity() {
        return (Identity<RelatedObjectCategorySchemeRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<RelatedObjectCategorySchemeRecord> getPrimaryKey() {
        return Keys.RELATED_OBJECT_CATEGORY_SCHEME_PKEY;
    }

    @Override
    public RelatedObjectCategoryScheme as(String alias) {
        return new RelatedObjectCategoryScheme(DSL.name(alias), this);
    }

    @Override
    public RelatedObjectCategoryScheme as(Name alias) {
        return new RelatedObjectCategoryScheme(alias, this);
    }

    @Override
    public RelatedObjectCategoryScheme as(Table<?> alias) {
        return new RelatedObjectCategoryScheme(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RelatedObjectCategoryScheme rename(String name) {
        return new RelatedObjectCategoryScheme(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RelatedObjectCategoryScheme rename(Name name) {
        return new RelatedObjectCategoryScheme(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RelatedObjectCategoryScheme rename(Table<?> name) {
        return new RelatedObjectCategoryScheme(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
