/*
 * This file is generated by jOOQ.
 */
package raido.db.jooq.api_svc.tables;


import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import raido.db.jooq.api_svc.ApiSvc;
import raido.db.jooq.api_svc.Keys;
import raido.db.jooq.api_svc.tables.records.RelatedObjectTypeSchemeRecord;

import java.util.function.Function;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RelatedObjectTypeScheme extends TableImpl<RelatedObjectTypeSchemeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>api_svc.related_object_type_scheme</code>
     */
    public static final RelatedObjectTypeScheme RELATED_OBJECT_TYPE_SCHEME = new RelatedObjectTypeScheme();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RelatedObjectTypeSchemeRecord> getRecordType() {
        return RelatedObjectTypeSchemeRecord.class;
    }

    /**
     * The column <code>api_svc.related_object_type_scheme.id</code>.
     */
    public final TableField<RelatedObjectTypeSchemeRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>api_svc.related_object_type_scheme.uri</code>.
     */
    public final TableField<RelatedObjectTypeSchemeRecord, String> URI = createField(DSL.name("uri"), SQLDataType.VARCHAR.nullable(false), this, "");

    private RelatedObjectTypeScheme(Name alias, Table<RelatedObjectTypeSchemeRecord> aliased) {
        this(alias, aliased, null);
    }

    private RelatedObjectTypeScheme(Name alias, Table<RelatedObjectTypeSchemeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>api_svc.related_object_type_scheme</code> table
     * reference
     */
    public RelatedObjectTypeScheme(String alias) {
        this(DSL.name(alias), RELATED_OBJECT_TYPE_SCHEME);
    }

    /**
     * Create an aliased <code>api_svc.related_object_type_scheme</code> table
     * reference
     */
    public RelatedObjectTypeScheme(Name alias) {
        this(alias, RELATED_OBJECT_TYPE_SCHEME);
    }

    /**
     * Create a <code>api_svc.related_object_type_scheme</code> table reference
     */
    public RelatedObjectTypeScheme() {
        this(DSL.name("related_object_type_scheme"), null);
    }

    public <O extends Record> RelatedObjectTypeScheme(Table<O> child, ForeignKey<O, RelatedObjectTypeSchemeRecord> key) {
        super(child, key, RELATED_OBJECT_TYPE_SCHEME);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ApiSvc.API_SVC;
    }

    @Override
    public Identity<RelatedObjectTypeSchemeRecord, Integer> getIdentity() {
        return (Identity<RelatedObjectTypeSchemeRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<RelatedObjectTypeSchemeRecord> getPrimaryKey() {
        return Keys.RELATED_OBJECT_TYPE_SCHEME_PKEY;
    }

    @Override
    public RelatedObjectTypeScheme as(String alias) {
        return new RelatedObjectTypeScheme(DSL.name(alias), this);
    }

    @Override
    public RelatedObjectTypeScheme as(Name alias) {
        return new RelatedObjectTypeScheme(alias, this);
    }

    @Override
    public RelatedObjectTypeScheme as(Table<?> alias) {
        return new RelatedObjectTypeScheme(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RelatedObjectTypeScheme rename(String name) {
        return new RelatedObjectTypeScheme(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RelatedObjectTypeScheme rename(Name name) {
        return new RelatedObjectTypeScheme(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RelatedObjectTypeScheme rename(Table<?> name) {
        return new RelatedObjectTypeScheme(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}