@startuml

' load the C4 PlantUML template  
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' for the database shape `ContainerDb`
!define ICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/

LAYOUT_TOP_DOWN()
LAYOUT_WITH_LEGEND()

title C4 Container diagram for Raido

Person_Ext(PublicUser, "Public User", "[anonymous]")
Person(SpUser, "Raido\nServicePoint User", "[SSO sign-in via OpenID Connect]")
System_Ext(SpInt, "Raido\nServicePoint Integrator", "[api-key authenticated]")
System_Ext(IdProvider, "ID Provider", "[Google / AAF / ORCiD]")
System_Ext(LocalHdlSvc, "Local Handle Service", "[ARDC DevOps]")


System_Boundary(raidC1, "Raid") {
  Container(PubClient, "pub-client", "any web tech\ncurrently uses app-client") 
  
  Container(RaidWebServer, "web server", "Cloudfront") 
  Container(RaidApiSvc, "raid-api-svc", "Spring REST API") 
}


System_Boundary(raidoC1, "Raido") {
  Container(AppClient, "app-client", "Raido UI -\nSinglePageApp") 
  
  Container(RaidoWebServer, "web server", "Cloudfront") 
  Container(RaidoApiSvc, "raido-api-svc", "Spring REST API") 
  ContainerDb(db, "Database", "RDS PostgreSQL")
}

 

Rel(PublicUser, PubClient, "Uses", "in browser")
Rel(SpUser, AppClient, "Uses", "in browser")
Rel(SpUser, IdProvider, "Identifies with", "HTTPS/OAuth2")
Rel(AppClient, RaidoWebServer, "Uses", "HTTPS")
Rel(PubClient, RaidWebServer, "Uses", "HTTPS")
Rel(RaidoWebServer, RaidoApiSvc, "Uses", "HTTPS")
Rel(RaidWebServer, RaidApiSvc, "Uses", "HTTPS")
Rel(RaidApiSvc, RaidoApiSvc, "read", "HTTPS")
Rel(SpInt, RaidoWebServer, "Uses", "HTTPS")
Rel(RaidoApiSvc, db, "read/write", "postgres:5432")
Rel(RaidoApiSvc, LocalHdlSvc, "mint", "HTTPS")
@enduml

