/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.api_svc.tables;


import au.org.raid.db.jooq.api_svc.ApiSvc;
import au.org.raid.db.jooq.api_svc.Keys;
import au.org.raid.db.jooq.api_svc.tables.records.AccessTypeSchemaRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccessTypeSchema extends TableImpl<AccessTypeSchemaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>api_svc.access_type_schema</code>
     */
    public static final AccessTypeSchema ACCESS_TYPE_SCHEMA = new AccessTypeSchema();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccessTypeSchemaRecord> getRecordType() {
        return AccessTypeSchemaRecord.class;
    }

    /**
     * The column <code>api_svc.access_type_schema.id</code>.
     */
    public final TableField<AccessTypeSchemaRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>api_svc.access_type_schema.uri</code>.
     */
    public final TableField<AccessTypeSchemaRecord, String> URI = createField(DSL.name("uri"), SQLDataType.VARCHAR.nullable(false), this, "");

    private AccessTypeSchema(Name alias, Table<AccessTypeSchemaRecord> aliased) {
        this(alias, aliased, null);
    }

    private AccessTypeSchema(Name alias, Table<AccessTypeSchemaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>api_svc.access_type_schema</code> table reference
     */
    public AccessTypeSchema(String alias) {
        this(DSL.name(alias), ACCESS_TYPE_SCHEMA);
    }

    /**
     * Create an aliased <code>api_svc.access_type_schema</code> table reference
     */
    public AccessTypeSchema(Name alias) {
        this(alias, ACCESS_TYPE_SCHEMA);
    }

    /**
     * Create a <code>api_svc.access_type_schema</code> table reference
     */
    public AccessTypeSchema() {
        this(DSL.name("access_type_schema"), null);
    }

    public <O extends Record> AccessTypeSchema(Table<O> child, ForeignKey<O, AccessTypeSchemaRecord> key) {
        super(child, key, ACCESS_TYPE_SCHEMA);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ApiSvc.API_SVC;
    }

    @Override
    public Identity<AccessTypeSchemaRecord, Integer> getIdentity() {
        return (Identity<AccessTypeSchemaRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<AccessTypeSchemaRecord> getPrimaryKey() {
        return Keys.ACCESS_TYPE_SCHEMA_PKEY;
    }

    @Override
    public AccessTypeSchema as(String alias) {
        return new AccessTypeSchema(DSL.name(alias), this);
    }

    @Override
    public AccessTypeSchema as(Name alias) {
        return new AccessTypeSchema(alias, this);
    }

    @Override
    public AccessTypeSchema as(Table<?> alias) {
        return new AccessTypeSchema(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AccessTypeSchema rename(String name) {
        return new AccessTypeSchema(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AccessTypeSchema rename(Name name) {
        return new AccessTypeSchema(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AccessTypeSchema rename(Table<?> name) {
        return new AccessTypeSchema(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
