/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.api_svc.tables;


import au.org.raid.db.jooq.api_svc.ApiSvc;
import au.org.raid.db.jooq.api_svc.Keys;
import au.org.raid.db.jooq.api_svc.tables.records.LanguageSchemaRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LanguageSchema extends TableImpl<LanguageSchemaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>api_svc.language_schema</code>
     */
    public static final LanguageSchema LANGUAGE_SCHEMA = new LanguageSchema();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LanguageSchemaRecord> getRecordType() {
        return LanguageSchemaRecord.class;
    }

    /**
     * The column <code>api_svc.language_schema.id</code>.
     */
    public final TableField<LanguageSchemaRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>api_svc.language_schema.uri</code>.
     */
    public final TableField<LanguageSchemaRecord, String> URI = createField(DSL.name("uri"), SQLDataType.VARCHAR.nullable(false), this, "");

    private LanguageSchema(Name alias, Table<LanguageSchemaRecord> aliased) {
        this(alias, aliased, null);
    }

    private LanguageSchema(Name alias, Table<LanguageSchemaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>api_svc.language_schema</code> table reference
     */
    public LanguageSchema(String alias) {
        this(DSL.name(alias), LANGUAGE_SCHEMA);
    }

    /**
     * Create an aliased <code>api_svc.language_schema</code> table reference
     */
    public LanguageSchema(Name alias) {
        this(alias, LANGUAGE_SCHEMA);
    }

    /**
     * Create a <code>api_svc.language_schema</code> table reference
     */
    public LanguageSchema() {
        this(DSL.name("language_schema"), null);
    }

    public <O extends Record> LanguageSchema(Table<O> child, ForeignKey<O, LanguageSchemaRecord> key) {
        super(child, key, LANGUAGE_SCHEMA);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ApiSvc.API_SVC;
    }

    @Override
    public Identity<LanguageSchemaRecord, Integer> getIdentity() {
        return (Identity<LanguageSchemaRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<LanguageSchemaRecord> getPrimaryKey() {
        return Keys.LANGUAGE_SCHEMA_PKEY;
    }

    @Override
    public LanguageSchema as(String alias) {
        return new LanguageSchema(DSL.name(alias), this);
    }

    @Override
    public LanguageSchema as(Name alias) {
        return new LanguageSchema(alias, this);
    }

    @Override
    public LanguageSchema as(Table<?> alias) {
        return new LanguageSchema(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public LanguageSchema rename(String name) {
        return new LanguageSchema(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LanguageSchema rename(Name name) {
        return new LanguageSchema(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public LanguageSchema rename(Table<?> name) {
        return new LanguageSchema(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
