/*
 * This file is generated by jOOQ.
 */
package raido.db.jooq.api_svc.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import raido.db.jooq.api_svc.tables.ApiToken;


/**
 * the id is used in the token generated, as well as issued and expiry, but the
 *   token itself is not stored
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApiTokenRecord extends UpdatableRecordImpl<ApiTokenRecord> implements Record5<Long, LocalDateTime, Long, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.api_token.id</code>.
     */
    public ApiTokenRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.api_token.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>api_svc.api_token.expiry</code>.
     */
    public ApiTokenRecord setExpiry(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.api_token.expiry</code>.
     */
    public LocalDateTime getExpiry() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>api_svc.api_token.service_point_id</code>.
     */
    public ApiTokenRecord setServicePointId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.api_token.service_point_id</code>.
     */
    public Long getServicePointId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>api_svc.api_token.description</code>.
     */
    public ApiTokenRecord setDescription(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.api_token.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>api_svc.api_token.date_created</code>.
     */
    public ApiTokenRecord setDateCreated(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.api_token.date_created</code>.
     */
    public LocalDateTime getDateCreated() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, LocalDateTime, Long, String, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, LocalDateTime, Long, String, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ApiToken.API_TOKEN.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return ApiToken.API_TOKEN.EXPIRY;
    }

    @Override
    public Field<Long> field3() {
        return ApiToken.API_TOKEN.SERVICE_POINT_ID;
    }

    @Override
    public Field<String> field4() {
        return ApiToken.API_TOKEN.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return ApiToken.API_TOKEN.DATE_CREATED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getExpiry();
    }

    @Override
    public Long component3() {
        return getServicePointId();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public LocalDateTime component5() {
        return getDateCreated();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getExpiry();
    }

    @Override
    public Long value3() {
        return getServicePointId();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public LocalDateTime value5() {
        return getDateCreated();
    }

    @Override
    public ApiTokenRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ApiTokenRecord value2(LocalDateTime value) {
        setExpiry(value);
        return this;
    }

    @Override
    public ApiTokenRecord value3(Long value) {
        setServicePointId(value);
        return this;
    }

    @Override
    public ApiTokenRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ApiTokenRecord value5(LocalDateTime value) {
        setDateCreated(value);
        return this;
    }

    @Override
    public ApiTokenRecord values(Long value1, LocalDateTime value2, Long value3, String value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ApiTokenRecord
     */
    public ApiTokenRecord() {
        super(ApiToken.API_TOKEN);
    }

    /**
     * Create a detached, initialised ApiTokenRecord
     */
    public ApiTokenRecord(Long id, LocalDateTime expiry, Long servicePointId, String description, LocalDateTime dateCreated) {
        super(ApiToken.API_TOKEN);

        setId(id);
        setExpiry(expiry);
        setServicePointId(servicePointId);
        setDescription(description);
        setDateCreated(dateCreated);
    }
}
