/*
 * This file is generated by jOOQ.
 */
package raido.db.jooq.api_svc.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import raido.db.jooq.api_svc.tables.RelatedObjectType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RelatedObjectTypeRecord extends UpdatableRecordImpl<RelatedObjectTypeRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.related_object_type.name</code>.
     */
    public RelatedObjectTypeRecord setName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.related_object_type.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>api_svc.related_object_type.description</code>.
     */
    public RelatedObjectTypeRecord setDescription(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.related_object_type.description</code>.
     */
    public String getDescription() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.related_object_type.url</code>.
     */
    public RelatedObjectTypeRecord setUrl(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.related_object_type.url</code>.
     */
    public String getUrl() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return RelatedObjectType.RELATED_OBJECT_TYPE.NAME;
    }

    @Override
    public Field<String> field2() {
        return RelatedObjectType.RELATED_OBJECT_TYPE.DESCRIPTION;
    }

    @Override
    public Field<String> field3() {
        return RelatedObjectType.RELATED_OBJECT_TYPE.URL;
    }

    @Override
    public String component1() {
        return getName();
    }

    @Override
    public String component2() {
        return getDescription();
    }

    @Override
    public String component3() {
        return getUrl();
    }

    @Override
    public String value1() {
        return getName();
    }

    @Override
    public String value2() {
        return getDescription();
    }

    @Override
    public String value3() {
        return getUrl();
    }

    @Override
    public RelatedObjectTypeRecord value1(String value) {
        setName(value);
        return this;
    }

    @Override
    public RelatedObjectTypeRecord value2(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public RelatedObjectTypeRecord value3(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public RelatedObjectTypeRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RelatedObjectTypeRecord
     */
    public RelatedObjectTypeRecord() {
        super(RelatedObjectType.RELATED_OBJECT_TYPE);
    }

    /**
     * Create a detached, initialised RelatedObjectTypeRecord
     */
    public RelatedObjectTypeRecord(String name, String description, String url) {
        super(RelatedObjectType.RELATED_OBJECT_TYPE);

        setName(name);
        setDescription(description);
        setUrl(url);
    }
}
