/*
 * This file is generated by jOOQ.
 */
package raido.db.jooq.api_svc.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import raido.db.jooq.api_svc.tables.Subject;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubjectRecord extends UpdatableRecordImpl<SubjectRecord> implements Record4<String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.subject.id</code>.
     */
    public SubjectRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.subject.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>api_svc.subject.name</code>.
     */
    public SubjectRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.subject.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.subject.description</code>.
     */
    public SubjectRecord setDescription(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.subject.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>api_svc.subject.note</code>.
     */
    public SubjectRecord setNote(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.subject.note</code>.
     */
    public String getNote() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Subject.SUBJECT.ID;
    }

    @Override
    public Field<String> field2() {
        return Subject.SUBJECT.NAME;
    }

    @Override
    public Field<String> field3() {
        return Subject.SUBJECT.DESCRIPTION;
    }

    @Override
    public Field<String> field4() {
        return Subject.SUBJECT.NOTE;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public String component4() {
        return getNote();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public String value4() {
        return getNote();
    }

    @Override
    public SubjectRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public SubjectRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public SubjectRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public SubjectRecord value4(String value) {
        setNote(value);
        return this;
    }

    @Override
    public SubjectRecord values(String value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubjectRecord
     */
    public SubjectRecord() {
        super(Subject.SUBJECT);
    }

    /**
     * Create a detached, initialised SubjectRecord
     */
    public SubjectRecord(String id, String name, String description, String note) {
        super(Subject.SUBJECT);

        setId(id);
        setName(name);
        setDescription(description);
        setNote(note);
    }
}
