/*
 * This file is generated by jOOQ.
 */
package raido.db.jooq.api_svc.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;

import raido.db.jooq.api_svc.enums.AuthRequestStatus;
import raido.db.jooq.api_svc.enums.IdProvider;
import raido.db.jooq.api_svc.tables.UserAuthzRequest;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAuthzRequestRecord extends UpdatableRecordImpl<UserAuthzRequestRecord> implements Record11<Long, AuthRequestStatus, Long, String, String, IdProvider, String, Long, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.user_authz_request.id</code>.
     */
    public UserAuthzRequestRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.user_authz_request.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>api_svc.user_authz_request.status</code>.
     */
    public UserAuthzRequestRecord setStatus(AuthRequestStatus value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.user_authz_request.status</code>.
     */
    public AuthRequestStatus getStatus() {
        return (AuthRequestStatus) get(1);
    }

    /**
     * Setter for <code>api_svc.user_authz_request.serice_point_id</code>.
     */
    public UserAuthzRequestRecord setSericePointId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.user_authz_request.serice_point_id</code>.
     */
    public Long getSericePointId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>api_svc.user_authz_request.email</code>. Lowercase chars
     * only - db enforced
     */
    public UserAuthzRequestRecord setEmail(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.user_authz_request.email</code>. Lowercase chars
     * only - db enforced
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>api_svc.user_authz_request.client_id</code>.
     */
    public UserAuthzRequestRecord setClientId(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.user_authz_request.client_id</code>.
     */
    public String getClientId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>api_svc.user_authz_request.id_provider</code>.
     */
    public UserAuthzRequestRecord setIdProvider(IdProvider value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.user_authz_request.id_provider</code>.
     */
    public IdProvider getIdProvider() {
        return (IdProvider) get(5);
    }

    /**
     * Setter for <code>api_svc.user_authz_request.subject</code>.
     */
    public UserAuthzRequestRecord setSubject(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.user_authz_request.subject</code>.
     */
    public String getSubject() {
        return (String) get(6);
    }

    /**
     * Setter for <code>api_svc.user_authz_request.responding_user</code>. not
     * set until approved or rejected
     */
    public UserAuthzRequestRecord setRespondingUser(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.user_authz_request.responding_user</code>. not
     * set until approved or rejected
     */
    public Long getRespondingUser() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>api_svc.user_authz_request.description</code>.
     */
    public UserAuthzRequestRecord setDescription(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.user_authz_request.description</code>.
     */
    public String getDescription() {
        return (String) get(8);
    }

    /**
     * Setter for <code>api_svc.user_authz_request.date_requested</code>.
     */
    public UserAuthzRequestRecord setDateRequested(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.user_authz_request.date_requested</code>.
     */
    public LocalDateTime getDateRequested() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>api_svc.user_authz_request.date_responded</code>. not
     * set until approved or rejected
     */
    public UserAuthzRequestRecord setDateResponded(LocalDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.user_authz_request.date_responded</code>. not
     * set until approved or rejected
     */
    public LocalDateTime getDateResponded() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, AuthRequestStatus, Long, String, String, IdProvider, String, Long, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, AuthRequestStatus, Long, String, String, IdProvider, String, Long, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserAuthzRequest.USER_AUTHZ_REQUEST.ID;
    }

    @Override
    public Field<AuthRequestStatus> field2() {
        return UserAuthzRequest.USER_AUTHZ_REQUEST.STATUS;
    }

    @Override
    public Field<Long> field3() {
        return UserAuthzRequest.USER_AUTHZ_REQUEST.SERICE_POINT_ID;
    }

    @Override
    public Field<String> field4() {
        return UserAuthzRequest.USER_AUTHZ_REQUEST.EMAIL;
    }

    @Override
    public Field<String> field5() {
        return UserAuthzRequest.USER_AUTHZ_REQUEST.CLIENT_ID;
    }

    @Override
    public Field<IdProvider> field6() {
        return UserAuthzRequest.USER_AUTHZ_REQUEST.ID_PROVIDER;
    }

    @Override
    public Field<String> field7() {
        return UserAuthzRequest.USER_AUTHZ_REQUEST.SUBJECT;
    }

    @Override
    public Field<Long> field8() {
        return UserAuthzRequest.USER_AUTHZ_REQUEST.RESPONDING_USER;
    }

    @Override
    public Field<String> field9() {
        return UserAuthzRequest.USER_AUTHZ_REQUEST.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return UserAuthzRequest.USER_AUTHZ_REQUEST.DATE_REQUESTED;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return UserAuthzRequest.USER_AUTHZ_REQUEST.DATE_RESPONDED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public AuthRequestStatus component2() {
        return getStatus();
    }

    @Override
    public Long component3() {
        return getSericePointId();
    }

    @Override
    public String component4() {
        return getEmail();
    }

    @Override
    public String component5() {
        return getClientId();
    }

    @Override
    public IdProvider component6() {
        return getIdProvider();
    }

    @Override
    public String component7() {
        return getSubject();
    }

    @Override
    public Long component8() {
        return getRespondingUser();
    }

    @Override
    public String component9() {
        return getDescription();
    }

    @Override
    public LocalDateTime component10() {
        return getDateRequested();
    }

    @Override
    public LocalDateTime component11() {
        return getDateResponded();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public AuthRequestStatus value2() {
        return getStatus();
    }

    @Override
    public Long value3() {
        return getSericePointId();
    }

    @Override
    public String value4() {
        return getEmail();
    }

    @Override
    public String value5() {
        return getClientId();
    }

    @Override
    public IdProvider value6() {
        return getIdProvider();
    }

    @Override
    public String value7() {
        return getSubject();
    }

    @Override
    public Long value8() {
        return getRespondingUser();
    }

    @Override
    public String value9() {
        return getDescription();
    }

    @Override
    public LocalDateTime value10() {
        return getDateRequested();
    }

    @Override
    public LocalDateTime value11() {
        return getDateResponded();
    }

    @Override
    public UserAuthzRequestRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserAuthzRequestRecord value2(AuthRequestStatus value) {
        setStatus(value);
        return this;
    }

    @Override
    public UserAuthzRequestRecord value3(Long value) {
        setSericePointId(value);
        return this;
    }

    @Override
    public UserAuthzRequestRecord value4(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public UserAuthzRequestRecord value5(String value) {
        setClientId(value);
        return this;
    }

    @Override
    public UserAuthzRequestRecord value6(IdProvider value) {
        setIdProvider(value);
        return this;
    }

    @Override
    public UserAuthzRequestRecord value7(String value) {
        setSubject(value);
        return this;
    }

    @Override
    public UserAuthzRequestRecord value8(Long value) {
        setRespondingUser(value);
        return this;
    }

    @Override
    public UserAuthzRequestRecord value9(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public UserAuthzRequestRecord value10(LocalDateTime value) {
        setDateRequested(value);
        return this;
    }

    @Override
    public UserAuthzRequestRecord value11(LocalDateTime value) {
        setDateResponded(value);
        return this;
    }

    @Override
    public UserAuthzRequestRecord values(Long value1, AuthRequestStatus value2, Long value3, String value4, String value5, IdProvider value6, String value7, Long value8, String value9, LocalDateTime value10, LocalDateTime value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserAuthzRequestRecord
     */
    public UserAuthzRequestRecord() {
        super(UserAuthzRequest.USER_AUTHZ_REQUEST);
    }

    /**
     * Create a detached, initialised UserAuthzRequestRecord
     */
    public UserAuthzRequestRecord(Long id, AuthRequestStatus status, Long sericePointId, String email, String clientId, IdProvider idProvider, String subject, Long respondingUser, String description, LocalDateTime dateRequested, LocalDateTime dateResponded) {
        super(UserAuthzRequest.USER_AUTHZ_REQUEST);

        setId(id);
        setStatus(status);
        setSericePointId(sericePointId);
        setEmail(email);
        setClientId(clientId);
        setIdProvider(idProvider);
        setSubject(subject);
        setRespondingUser(respondingUser);
        setDescription(description);
        setDateRequested(dateRequested);
        setDateResponded(dateResponded);
    }
}
