/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.enums;


import au.org.raid.db.jooq.ApiSvc;
import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum UserRole implements EnumType {

    OPERATOR("OPERATOR"),

    SP_ADMIN("SP_ADMIN"),

    SP_USER("SP_USER"),

    API("API");

    private final String literal;

    private UserRole(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return ApiSvc.API_SVC;
    }

    @Override
    public String getName() {
        return "user_role";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static UserRole lookupLiteral(String literal) {
        return EnumType.lookupLiteral(UserRole.class, literal);
    }
}
